// "use client";

import "./globals.css";
import { Cairo } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Providers } from "./../redux/Provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";
import GoogleAnalytics from "@/components/googleAnlytics/GoogleAnlytics";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Dr.Ahmed Galal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleAnalytics />
      <body className={cairo.className}>
        <Providers>
          <ToastContainer />
          {children}
        </Providers>
      </body>
    </html>
  );
}
