"use client";

import './globals.css'
import { Cairo } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
// import NavbarHeader from '@/components/navbar/Navbar';
import { Providers } from './../redux/Provider';
import Footer from '@/components/Footer/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Dr.Ahmed Galal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        {/* <NavbarHeader/> */}

        <Providers>
            <ToastContainer/>
            {children}
        </Providers>
        {/* <Footer/> */}
        </body>
    </html>
  );
}
