"use client";

import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';
 import { Providers } from './../redux/Provider';
 import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Cairo } from 'next/font/google'

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Dr.Ahmed Galal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <Providers>
            <ToastContainer/>
            {children}
        </Providers>
        </body>
    </html>
  );
}
